services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    volumes:
      - ./frontend:/usr/src/app
    command: ["npm", "run", "dev", "--", "--host"]
